server:
  port: 80

spring:
  application:
    name: cloud-order-service     #微服务名称就是注册进eureka的名字

eureka:
  client:
    register-with-eureka: true      #true表示将自己注册进EurekaServer
    fetch-registry: true        #true,表示从EurekaServer抓取已有的注册信息；单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #单机版  defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

